apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-auth.name" . }}
data:
  auth_config.yml: |
    server:
      addr: ":{{ .Values.service.targetPort }}"
    token:
      issuer: "{{ .Values.configmap.data.token.issuer }}"  # Must match issuer in the Registry config.
      expiration: {{ .Values.configmap.data.token.expiration }}
{{- if .Values.secret.secretName }}
      certificate: "/config/certs/{{ default "tls.crt" .Values.secret.certificateFileName }}"
      key: "/config/certs/{{ default "tls.key" .Values.secret.keyFileName }}"
{{- else }}
      certificate: "/config/certs/server.pem"
      key: "/config/certs/server.key"
{{- end }}
{{- if .Values.configmap.data.token.disableLegacyKeyId }}
      disable_legacy_key_id: {{ .Values.configmap.data.token.disableLegacyKeyId }}
{{- end }}
    users:
      {{ .Values.configmap.data.users | toYaml | nindent 6 }}
    acl:
      {{ .Values.configmap.data.acl | toYaml | nindent 6 }}
