server:
  addr: :5001
  certificate: /path/to/server.pem 
  key: /path/to/server.key
token:
  issuer: Acme auth server
  expiration: 900
users:
  "": {}
ldap_auth:
  addr: 16.217.2.55:389
  start_tls: true
  base: o=example.com
  filter: (|(&(uid=${account})(objectClass=person))(&(cn=${account})(objectClass=Application)))
  # in case bind DN and password is required for querying directory server, the password is Base64 encoded
  bind_dn: uid=readonlyuser,ou=people,o=hp.com
  password: MTIz
acl:
- match:
    account: ""
  actions: [pull]
- match:
    account: /.+/
  actions: ['*']
