apiVersion: v2
appVersion: "1.8.0"
description: Docker Registry V2 authentication server
name: docker-auth
version: 1.4.0
keywords:
- docker
- registry
- docker-auth
- docker-registry
- token
home: https://github.com/cesanta/docker_auth
sources:
- https://github.com/cesanta/docker_auth
maintainers:
- name: duyanghao
  email: 1294057873@qq.com
- name: pfisterer
  email: github@farberg.de
engine: gotpl
